name: Build and deploy Docker container to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: docker build -t demo-app:v2 .

      - name: Tag Docker image
        run: docker tag demo-app:v2 838596736137.dkr.ecr.us-east-1.amazonaws.com/app/demo-app:v2

      - name: Push Docker image to Amazon ECR
        run: docker push 838596736137.dkr.ecr.us-east-1.amazonaws.com/app/demo-app:v2

      - name: Pull Docker image from Amazon ECR
        run: docker pull 838596736137.dkr.ecr.us-east-1.amazonaws.com/app/demo-app:v2

      - name: Run Docker container
        run: docker run -p 80:3000 838596736137.dkr.ecr.us-east-1.amazonaws.com/app/demo-app:v2
        